apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: redis-reader
  description: Used to read redis streams while running dapr locally
  tags:
    - redis
    - dapr
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: public-websites
